.de EX
.ne 5
.if n .sp 1
.if t .sp .5
.nf
.in +.5i
..
.de EE
.fi
.in -.5i
.if n .sp 8
.if t .sp .5
..
.TH autohosts 8 "May 23, 2019"
.SH NAME
Autohosts \- Block Firefox telemetry, Google snooping and web trackers at the root.
.SH SYNOPSIS
.B autohosts
.PP
Make your web browsing more private and secure by blocking known trackers and malware.
.SH DESCRIPTION
No config necessary - works out of the box!
.SS "Command reference:"
.TP
\fBapt remove autohosts\fR
Uninstall Autohosts and generate a backup of /etc/hosts in /tmp.
.TP
.SH SEE ALSO
None
.SH BUGS
See/report bugs at https://github.com/angela-d/autohosts
.SH AUTHOR
The text for this page was written by Angela <angelad@disroot.org> for the Debian GNU/Linux system (but may be used by
others).
.SH COPYRIGHT
Copyright  (C) 2019 Angela.  License GPLv3: GNU
GPL version 2 only <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
