#!/bin/bash
set -e

# copy the custom_filters into the user's home directory
# get the non-root user, so we can add the custom filters for them
REGUSER=$(last | grep "logged in" | grep -o '^\S*')
HOME_USER="/home/$REGUSER/autohosts/"

mkdir "$HOME_USER" && cp /usr/include/autohosts/custom_filters "$HOME_USER" && chown "$REGUSER:$REGUSER" -R "$HOME_USER"

# run autohosts after installing
autohosts
